version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hodowanko
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hodowanko
      - REACT_APP_API_URL="http://127.0.0.1:3001"
  #
volumes:
  db-data:
